import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<string, Record<Language, string>> = {
  // Navigation
  'nav.personal': { en: 'Personal', es: 'Personal' },
  'nav.business': { en: 'Business', es: 'Negocios' },
  'nav.resources': { en: 'Resources', es: 'Recursos' },
  'nav.about': { en: 'About', es: 'Nosotros' },
  'nav.atm': { en: 'ATM & Branch', es: 'Cajeros y Sucursales' },
  'nav.support': { en: 'Customer Service', es: 'Atención al Cliente' },
  'nav.search': { en: 'Search', es: 'Buscar' },
  'nav.search_placeholder': { en: 'Ask anything...', es: 'Pregunta lo que sea...' },
  'nav.language': { en: 'Español', es: 'English' },
  'nav.menu.open': { en: 'Open menu', es: 'Abrir menú' },
  'nav.menu.close': { en: 'Close menu', es: 'Cerrar menú' },

  // Live Assistant
  'live.title': { en: 'Lamar Assistant', es: 'Asistente Lamar' },
  'live.offline': { en: 'OFFLINE', es: 'DESCONECTADO' },
  'live.retry': { en: 'Retry', es: 'Reintentar' },
  'live.console': { en: 'Check console for details.', es: 'Revise la consola para detalles.' },
  'live.btn.start': { en: 'Chat with Assistant', es: 'Hablar con Asistente' },
  'live.status.connecting': { en: 'Connecting...', es: 'Conectando...' },
  'live.status.listening': { en: 'Listening...', es: 'Escuchando...' },
  'live.status.speaking': { en: 'Speaking...', es: 'Hablando...' },
  'live.error': { en: 'Connection failed. Please try again.', es: 'Conexión fallida. Intente de nuevo.' },
  'live.disclaimer': { en: 'AI Assistant can make mistakes.', es: 'El asistente de IA puede cometer errores.' },

  // Search Overlay
  'search.modal.placeholder': { en: 'Ask about rates, hours, or services...', es: 'Pregunte sobre tasas, horarios o servicios...' },
  'search.modal.searching': { en: 'Searching...', es: 'Buscando...' },
  'search.modal.sources': { en: 'Sources', es: 'Fuentes' },
  'search.modal.error': { en: 'Sorry, I encountered an error. Please try again.', es: 'Lo siento, encontré un error. Por favor inténtelo de nuevo.' },
  'search.modal.default': { en: 'How can I help you today?', es: '¿Cómo puedo ayudarle hoy?' },
  'search.modal.grounding_info': { en: 'Answers generated by AI using Google Search.', es: 'Respuestas generadas por IA usando Google Search.' },
  'search.err.voice': { en: 'Voice search not supported in this browser.', es: 'Búsqueda por voz no soportada en este navegador.' },
  'search.err.hear': { en: 'Could not hear you. Please try again.', es: 'No pude escucharle. Por favor intente de nuevo.' },

  // Smart Location Search
  'loc.ai.placeholder': { en: 'Ask AI: "Find ATMs near downtown Paris, TX"', es: 'Pregunte a la IA: "Buscar cajeros cerca del centro de Paris, TX"' },
  'loc.ai.btn': { en: 'Ask Maps', es: 'Preguntar a Maps' },
  'loc.ai.locating': { en: 'Locating you...', es: 'Ubicándolo...' },
  'loc.ai.searching': { en: 'Searching Google Maps...', es: 'Buscando en Google Maps...' },
  'loc.ai.results': { en: 'AI Results from Google Maps', es: 'Resultados de IA de Google Maps' },
  'loc.ai.disclaimer': { en: 'Grounding provided by Google Maps.', es: 'Información proporcionada por Google Maps.' },
  'loc.smart': { en: 'Smart Locator', es: 'Localizador Inteligente' },
  'loc.list.header': { en: 'Lamar National Locations', es: 'Ubicaciones Lamar National' },
  'loc.appt': { en: 'By Appointment', es: 'Con Cita' },
  'loc.feat.atm': { en: 'ATM', es: 'Cajero' },
  'loc.feat.lobby': { en: 'Lobby', es: 'Vestíbulo' },
  'loc.feat.drivethru': { en: 'Drive-Thru', es: 'Autobanco' },
  'loc.feat.safedeposit': { en: 'Safe Deposit', es: 'Cajas de Seguridad' },
  'loc.feat.commercial': { en: 'Commercial Lending', es: 'Préstamos Comerciales' },
  'loc.feat.lpo': { en: 'LPO', es: 'Oficina de Préstamos' },

  // Calculator
  'calc.mortgage.title': { en: 'Smart Mortgage Calculator', es: 'Calculadora de Hipoteca Inteligente' },
  'calc.label.amount': { en: 'Loan Amount ($)', es: 'Monto del Préstamo ($)' },
  'calc.label.rate': { en: 'Interest Rate (%)', es: 'Tasa de Interés (%)' },
  'calc.label.term': { en: 'Loan Term (Years)', es: 'Plazo (Años)' },
  'calc.label.down': { en: 'Down Payment ($)', es: 'Pago Inicial ($)' },
  'calc.btn.calculate': { en: 'Calculate Payment', es: 'Calcular Pago' },
  'calc.result.monthly': { en: 'Estimated Monthly Payment', es: 'Pago Mensual Estimado' },
  'calc.btn.ai': { en: 'Get AI Insights', es: 'Obtener Análisis de IA' },
  'calc.ai.loading': { en: 'Analyzing scenario...', es: 'Analizando escenario...' },
  'calc.ai.title': { en: 'AI Financial Insights', es: 'Análisis Financiero de IA' },
  'calc.back': { en: 'Back to Resources', es: 'Volver a Recursos' },
  'res.btn.mortgage': { en: 'Open Mortgage Calculator', es: 'Abrir Calculadora de Hipoteca' },
  'res.btn.security': { en: 'Visit Security Center', es: 'Visitar Centro de Seguridad' },
  'res.calc.years': { en: 'Years', es: 'Años' },
  'res.calc.note': { en: '*Principal & Interest only', es: '*Solo Capital e Interés' },

  // Hero
  'hero.title': { en: 'Banking As Big As Texas.', es: 'Banca tan grande como Texas.' },
  'hero.subtitle': { en: 'Experience the difference of a bank that knows your name, understands your roots, and grows with your community.', es: 'Experimente la diferencia de un banco que conoce su nombre, entiende sus raíces y crece con su comunidad.' },
  'hero.cta.open': { en: 'Open an Account', es: 'Abrir una Cuenta' },
  'hero.cta.find': { en: 'Find a Branch', es: 'Buscar Sucursal' },

  // Login
  'login.welcome': { en: 'Welcome', es: 'Bienvenido' },
  'login.user': { en: 'Username', es: 'Usuario' },
  'login.pass': { en: 'Password', es: 'Contraseña' },
  'login.remember': { en: 'Remember me', es: 'Recordarme' },
  'login.token': { en: 'Use Token?', es: '¿Usar Token?' },
  'login.signin': { en: 'Sign In', es: 'Iniciar Sesión' },
  'login.forgot': { en: 'Forgot username/password?', es: '¿Olvidó usuario/contraseña?' },
  'login.enroll': { en: 'Not enrolled? Sign up now.', es: '¿No inscrito? Regístrese ahora.' },

  // Services
  'service.checking': { en: 'Checking', es: 'Cheques' },
  'service.savings': { en: 'Savings', es: 'Ahorros' },
  'service.homeLoans': { en: 'Home Loans', es: 'Hipotecas' },
  'service.autoLoans': { en: 'Auto Loans', es: 'Préstamos de Auto' },
  'service.business': { en: 'Business', es: 'Negocios' },
  'service.investing': { en: 'Investing', es: 'Inversiones' },
  'service.security': { en: 'Security', es: 'Seguridad' },
  'service.mobile': { en: 'Mobile App', es: 'Banca Móvil' },

  // Service Grid Specific
  'service.grid.checking': { en: 'Checking', es: 'Cheques' },
  'service.grid.savings': { en: 'Savings', es: 'Ahorros' },
  'service.grid.homeLoans': { en: 'Home Loans', es: 'Hipotecas' },
  'service.grid.autoLoans': { en: 'Auto Loans', es: 'Autos' },
  'service.grid.business': { en: 'Business', es: 'Empresas' },
  'service.grid.investing': { en: 'Investing', es: 'Inversiones' },
  'service.grid.security': { en: 'Security', es: 'Seguridad' },
  'service.grid.mobile': { en: 'Mobile App', es: 'App Móvil' },

  // Home Content
  'home.wellness': { en: 'Financial Wellness & Resources', es: 'Bienestar Financiero y Recursos' },
  'home.balance.title': { en: 'Check your balance', es: 'Revise su saldo' },
  'home.balance.desc': { en: 'Stay on top of your finances with our easy-to-use mobile tools.', es: 'Manténgase al tanto de sus finanzas con nuestras herramientas móviles fáciles de usar.' },
  'home.balance.link': { en: 'Learn more', es: 'Más información' },
  'home.refinance.title': { en: 'Refinance your home', es: 'Refinancie su hogar' },
  'home.refinance.desc': { en: "See if you can save money by taking advantage of today's rates.", es: 'Vea si puede ahorrar dinero aprovechando las tasas de hoy.' },
  'home.refinance.link': { en: 'See rates', es: 'Ver tasas' },
  'home.biz.title': { en: 'Business Solutions', es: 'Soluciones de Negocios' },
  'home.biz.desc': { en: 'Grow your business with customized lending and cash management.', es: 'Haga crecer su negocio con préstamos personalizados y gestión de efectivo.' },
  'home.biz.link': { en: 'Get started', es: 'Comenzar' },

  // Footer
  'footer.follow': { en: 'Follow Us', es: 'Síguenos' },
  'footer.locations': { en: 'Our Locations', es: 'Nuestras Ubicaciones' },
  'footer.loc.paris': { en: 'Paris - Main Bank', es: 'Paris - Banco Principal' },
  'footer.hq': { en: 'Headquarters', es: 'Sede Central' },
  'footer.viewAll': { en: 'View All Locations', es: 'Ver Todas las Ubicaciones' },
  'footer.about': { en: 'About Us', es: 'Sobre Nosotros' },
  'footer.resources': { en: 'Resources', es: 'Recursos' },
  'footer.copyright': { en: 'Lamar National Bank. Member FDIC. Equal Housing Lender.', es: 'Lamar National Bank. Miembro FDIC. Prestamista de Vivienda Equitativa.' },
  'footer.privacy': { en: 'Privacy Policy', es: 'Política de Privacidad' },
  'footer.terms': { en: 'Terms of Use', es: 'Términos de Uso' },
  'footer.security': { en: 'Security Center', es: 'Centro de Seguridad' },
  'footer.accessibility': { en: 'Accessibility', es: 'Accesibilidad' },
  'footer.careers': { en: 'Careers', es: 'Carreras' },
  'footer.news': { en: 'Newsroom', es: 'Noticias' },
  'footer.investor': { en: 'Investor Relations', es: 'Relaciones con Inversores' },
  'footer.community': { en: 'Community Giving', es: 'Apoyo Comunitario' },
  'footer.lost': { en: 'Report Lost/Stolen Card', es: 'Reportar Tarjeta Perdida' },
  'footer.story': { en: 'Our Story', es: 'Nuestra Historia' },
  'footer.contact': { en: 'Contact Support', es: 'Contactar Soporte' },
  'footer.dobNotice': { en: 'Texas Dept. of Banking Notice', es: 'Aviso del Dept. Bancario de Texas' },
  'footer.dobLink': { en: 'Texas Dept. of Banking', es: 'Dept. Bancario de Texas' },
  'footer.social.facebook': { en: 'Visit our Facebook page', es: 'Visite nuestra página de Facebook' },
  'footer.social.twitter': { en: 'Visit our Twitter profile', es: 'Visite nuestro perfil de Twitter' },
  'footer.social.instagram': { en: 'Visit our Instagram profile', es: 'Visite nuestro perfil de Instagram' },
  'footer.social.linkedin': { en: 'Visit our LinkedIn profile', es: 'Visite nuestro perfil de LinkedIn' },
  'footer.aria.call': { en: 'Call us at', es: 'Llámenos al' },
  'footer.aria.email': { en: 'Email us', es: 'Envíenos un correo' },

  // App Stores
  'app.store': { en: 'App Store', es: 'App Store' },
  'google.play': { en: 'Google Play', es: 'Google Play' },

  // Personal Page
  'personal.title': { en: 'Personal Banking', es: 'Banca Personal' },
  'personal.subtitle': { en: 'Financial solutions designed for your life, from your first checking account to your retirement.', es: 'Soluciones financieras diseñadas para su vida, desde su primera cuenta de cheques hasta su jubilación.' },
  'personal.checking.title': { en: 'Checking & Savings', es: 'Cheques y Ahorros' },
  'personal.checking.desc': { en: 'Whether you want a simple, fee-free account or interest-bearing options, we have the right account for you.', es: 'Ya sea que desee una cuenta simple y sin cargos u opciones con intereses, tenemos la cuenta adecuada para usted.' },
  'personal.checking.list1': { en: 'Free Debit Card', es: 'Tarjeta de débito gratuita' },
  'personal.checking.list2': { en: 'Online & Mobile Banking', es: 'Banca en línea y móvil' },
  'personal.checking.list3': { en: 'Overdraft Protection available', es: 'Protección contra sobregiros disponible' },
  'personal.checking.btn': { en: 'Compare Accounts', es: 'Comparar Cuentas' },
  'personal.lending.title': { en: 'Lending Solutions', es: 'Soluciones de Préstamos' },
  'personal.lending.desc': { en: 'Ready for that new car? Looking to buy your dream home? Our local decision-making makes the process fast.', es: '¿Listo para ese auto nuevo? ¿Busca comprar la casa de sus sueños? Nuestra toma de decisiones local hace que el proceso sea rápido.' },
  'personal.lending.auto': { en: 'Auto', es: 'Autos' },
  'personal.lending.mortgage': { en: 'Mortgage', es: 'Hipotecas' },
  'personal.lending.btn': { en: 'View Rates', es: 'Ver Tasas' },
  'personal.mobile.badge': { en: 'Mobile App', es: 'App Móvil' },
  'personal.mobile.title': { en: 'Bank from anywhere.', es: 'Banca desde cualquier lugar.' },
  'personal.mobile.desc': { en: 'Deposit checks, pay bills, and send money to friends with Zelle®—all from the Lamar National Bank mobile app.', es: 'Deposite cheques, pague facturas y envíe dinero a amigos con Zelle®, todo desde la aplicación móvil de Lamar National Bank.' },

  // Goal Planner
  'planner.title': { en: 'Smart Savings Goal Planner', es: 'Planificador de Metas de Ahorro Inteligente' },
  'planner.subtitle': { en: 'Tell us what you are saving for, and our AI will build a custom timeline for you.', es: 'Díganos para qué está ahorrando y nuestra IA creará un cronograma personalizado para usted.' },
  'planner.placeholder': { en: 'Describe your goal in detail (amount, timeline, etc.)...', es: 'Describa su meta en detalle (monto, plazo, etc.)...' },
  'planner.btn.create': { en: 'Create My Plan', es: 'Crear Mi Plan' },
  'planner.creating': { en: 'Designing your plan...', es: 'Diseñando su plan...' },
  'planner.monthly': { en: 'Monthly Target', es: 'Meta Mensual' },
  'planner.tips': { en: 'Smart Strategies', es: 'Estrategias Inteligentes' },
  'planner.timeline': { en: 'Your Roadmap', es: 'Su Hoja de Ruta' },
  'planner.disclaimer': { en: 'AI-generated plan for illustration purposes only.', es: 'Plan generado por IA solo con fines ilustrativos.' },
  'planner.quick.vacation': { en: 'Dream Vacation', es: 'Vacaciones de Ensueño' },
  'planner.quick.car': { en: 'New Car', es: 'Auto Nuevo' },
  'planner.quick.home': { en: 'New Home', es: 'Casa Nueva' },
  'planner.quick.emergency': { en: 'Emergency Fund', es: 'Fondo de Emergencia' },

  // Business Page
  'business.title': { en: 'Business Banking', es: 'Banca Comercial' },
  'business.subtitle': { en: 'We are more than just a bank; we are a strategic partner invested in the growth of your business.', es: 'Somos más que un banco; somos un socio estratégico invertido en el crecimiento de su negocio.' },
  'business.cta': { en: 'Contact a Commercial Lender', es: 'Contactar a un Prestamista Comercial' },
  'business.lending.title': { en: 'Commercial Lending', es: 'Préstamos Comerciales' },
  'business.lending.desc': { en: 'Lamar National Bank offers a variety of loan options to meet the needs of your growing business. From equipment financing to commercial real estate, our local decision makers are here to help.', es: 'Lamar National Bank ofrece una variedad de opciones de préstamos para satisfacer las necesidades de su negocio en crecimiento. Desde financiamiento de equipos hasta bienes raíces comerciales, nuestros tomadores de decisiones locales están aquí para ayudar.' },
  'business.re.title': { en: 'Real Estate', es: 'Bienes Raíces' },
  'business.re.desc': { en: 'Owner-occupied and investment property financing.', es: 'Financiamiento de propiedades ocupadas por el propietario y de inversión.' },
  'business.eq.title': { en: 'Equipment', es: 'Equipo' },
  'business.eq.desc': { en: 'Term loans for machinery, vehicles, and technology.', es: 'Préstamos a plazo para maquinaria, vehículos y tecnología.' },
  'business.loc.title': { en: 'Lines of Credit', es: 'Líneas de Crédito' },
  'business.loc.desc': { en: 'Working capital to manage cash flow fluctuations.', es: 'Capital de trabajo para gestionar las fluctuaciones del flujo de caja.' },
  'business.sba.title': { en: 'SBA Loans', es: 'Préstamos SBA' },
  'business.sba.desc': { en: 'Government-backed financing solutions.', es: 'Soluciones de financiamiento respaldadas por el gobierno.' },
  'business.treasury.title': { en: 'Treasury Management', es: 'Gestión de Tesorería' },
  'business.treasury.desc': { en: 'Optimize your cash flow with our suite of digital tools designed for efficiency and security.', es: 'Optimice su flujo de caja con nuestro conjunto de herramientas digitales diseñadas para la eficiencia y la seguridad.' },
  'business.treasury.list1': { en: 'Remote Deposit Capture', es: 'Captura Remota de Depósitos' },
  'business.treasury.list2': { en: 'ACH Origination', es: 'Originación ACH' },
  'business.treasury.list3': { en: 'Positive Pay Fraud Prevention', es: 'Prevención de Fraude Positive Pay' },
  'business.treasury.list4': { en: 'Merchant Services', es: 'Servicios para Comerciantes' },
  'business.sidebar.title': { en: 'Business Resources', es: 'Recursos Comerciales' },
  'business.team.title': { en: 'Meet the Team', es: 'Conozca al Equipo' },
  'business.team.desc': { en: 'Our commercial lenders have decades of experience in the Texas market.', es: 'Nuestros prestamistas comerciales tienen décadas de experiencia en el mercado de Texas.' },
  'business.team.link': { en: 'View Directory', es: 'Ver Directorio' },
  'business.rates.title': { en: 'Current Rates', es: 'Tasas Actuales' },
  'business.rates.desc': { en: 'View our competitive rates for savings and CDs.', es: 'Vea nuestras tasas competitivas para ahorros y CD.' },
  'business.rates.link': { en: 'Check Rates', es: 'Ver Tasas' },

  // Business Growth Strategist
  'biz.growth.title': { en: 'Business Growth Strategist', es: 'Estratega de Crecimiento Empresarial' },
  'biz.growth.subtitle': { en: 'AI-powered insights to take your enterprise to the next level.', es: 'Perspectivas impulsadas por IA para llevar su empresa al siguiente nivel.' },
  'biz.growth.industry': { en: 'Industry / Sector', es: 'Industria / Sector' },
  'biz.growth.focus': { en: 'Current Strategic Focus', es: 'Enfoque Estratégico Actual' },
  'biz.growth.revenue': { en: 'Annual Revenue ($)', es: 'Ingresos Anuales ($)' },
  'biz.growth.btn': { en: 'Generate Strategy', es: 'Generar Estrategia' },
  'biz.growth.analyzing': { en: 'Analyzing Market Data...', es: 'Analizando Datos de Mercado...' },
  'biz.growth.insight': { en: 'Strategic Insight', es: 'Perspectiva Estratégica' },
  'biz.growth.recommendation': { en: 'Recommended Solution', es: 'Solución Recomendada' },
  'biz.growth.steps': { en: 'Next Steps', es: 'Próximos Pasos' },

  // About Page
  'about.hero.title': { en: 'Relationship Banking Since 1933', es: 'Banca de Relaciones Desde 1933' },
  'about.hero.subtitle': { en: 'Deeply rooted in Texas, we believe in shaking hands, knowing names, and building futures together.', es: 'Profundamente arraigados en Texas, creemos en estrechar manos, conocer nombres y construir futuros juntos.' },
  'about.story.title': { en: 'Our Story', es: 'Nuestra Historia' },
  'about.story.p1': { en: 'Founded in the heart of Paris, Texas, Lamar National Bank has stood as a pillar of stability and growth for nearly a century. We navigated through economic shifts, technological revolutions, and community changes by staying true to one core principle: Service comes first.', es: 'Fundado en el corazón de Paris, Texas, Lamar National Bank se ha mantenido como un pilar de estabilidad y crecimiento durante casi un siglo. Navegamos a través de cambios económicos, revoluciones tecnológicas y cambios comunitarios manteniéndonos fieles a un principio fundamental: El servicio es lo primero.' },
  'about.story.p2': { en: 'Today, while we offer the sophisticated digital tools of a modern financial institution, we maintain the soul of a community bank. Our decisions are made locally, by people who live in your neighborhoods and shop at your stores.', es: 'Hoy, mientras ofrecemos las sofisticadas herramientas digitales de una institución financiera moderna, mantenemos el alma de un banco comunitario. Nuestras decisiones se toman localmente, por personas que viven en sus vecindarios y compran en sus tiendas.' },
  'about.val.longevity.title': { en: 'Longevity', es: 'Longevidad' },
  'about.val.longevity.desc': { en: 'Serving generations of Texans with unwavering stability.', es: 'Sirviendo a generaciones de tejanos con estabilidad inquebrantable.' },
  'about.val.community.title': { en: 'Community', es: 'Comunidad' },
  'about.val.community.desc': { en: 'Reinvesting deposits back into local businesses and families.', es: 'Reinvertir depósitos en empresas y familias locales.' },
  'about.val.service.title': { en: 'Service', es: 'Servicio' },
  'about.val.service.desc': { en: 'Real people answering phones, not endless robot menus.', es: 'Personas reales contestando teléfonos, no menús de robots interminables.' },
  'about.lead.title': { en: 'Led by Locals', es: 'Liderado por Locales' },
  'about.lead.desc': { en: 'Our executive team and board of directors are comprised of local business leaders who understand the unique economic landscape of Texas.', es: 'Nuestro equipo ejecutivo y junta directiva están compuestos por líderes empresariales locales que entienden el panorama económico único de Texas.' },
  'about.lead.btn': { en: 'View Leadership Team', es: 'Ver Equipo de Liderazgo' },

  // Resources Page
  'resources.hero.title': { en: 'Resources & Tools', es: 'Recursos y Herramientas' },
  'resources.hero.subtitle': { en: 'Everything you need to manage your financial life securely and effectively.', es: 'Todo lo que necesita para administrar su vida financiera de manera segura y efectiva.' },
  'resources.calc.title': { en: 'Financial Calculators', es: 'Calculadoras Financieras' },
  'resources.calc.desc': { en: 'Plan for your future with our interactive calculators for mortgages, savings, and loans.', es: 'Planifique su futuro con nuestras calculadoras interactivas para hipotecas, ahorros y préstamos.' },
  'resources.sec.title': { en: 'Security Center', es: 'Centro de Seguridad' },
  'resources.sec.desc': { en: 'Learn how to protect yourself from fraud and what to do if you suspect suspicious activity.', es: 'Aprenda cómo protegerse del fraude y qué hacer si sospecha actividad sospechosa.' },
  'resources.edu.title': { en: 'Financial Education', es: 'Educación Financiera' },
  'resources.edu.desc': { en: 'Articles and guides to help you make informed decisions about your money.', es: 'Artículos y guías para ayudarle a tomar decisiones informadas sobre su dinero.' },
  'resources.edu.btn': { en: 'Visit Education Center', es: 'Visitar Centro Educativo' },

  // Compare Accounts Page
  'compare.title': { en: 'Compare Checking Accounts', es: 'Comparar Cuentas de Cheques' },
  'compare.subtitle': { en: 'Find the perfect account for your financial lifestyle.', es: 'Encuentre la cuenta perfecta para su estilo de vida financiero.' },
  'compare.acct.free': { en: 'Free Checking', es: 'Cheques Gratis' },
  'compare.acct.interest': { en: 'Interest Checking', es: 'Cheques con Interés' },
  'compare.acct.premier': { en: 'Premier Checking', es: 'Cheques Premier' },
  'compare.row.fee': { en: 'Monthly Service Fee', es: 'Cargo Mensual' },
  'compare.row.min': { en: 'Minimum Balance to Avoid Fee', es: 'Saldo Mínimo para Evitar Cargo' },
  'compare.row.interest': { en: 'Interest Earned', es: 'Interés Ganado' },
  'compare.row.atm': { en: 'ATM Fees', es: 'Tarifas de Cajero' },
  'compare.row.digital': { en: 'Online & Mobile Banking', es: 'Banca en Línea y Móvil' },
  'compare.val.free': { en: 'Free', es: 'Gratis' },
  'compare.val.waivable': { en: 'Waivable', es: 'Renunciable' },
  'compare.val.refunds': { en: 'Refunds up to $25/mo', es: 'Reembolsos hasta $25/mes' },
  'compare.btn.open': { en: 'Open Now', es: 'Abrir Ahora' },
  'compare.disclaimer': { en: 'Fees subject to change. See fee schedule for details.', es: 'Tarifas sujetas a cambios. Consulte el programa de tarifas para más detalles.' },
  'compare.features': { en: 'Features', es: 'Características' },
  'compare.desc.free': { en: 'Best for everyday basics', es: 'Lo mejor para lo básico' },
  'compare.desc.int': { en: 'Earn while you spend', es: 'Gane mientras gasta' },
  'compare.desc.prem': { en: 'Maximum benefits', es: 'Beneficios máximos' },
  'compare.val.std': { en: 'Standard', es: 'Estándar' },
  'compare.val.high': { en: 'Higher Rate', es: 'Tasa Más Alta' },
  'compare.badge.pop': { en: 'Popular', es: 'Popular' },
  'compare.advisor.label': { en: 'AI Advisor', es: 'Asesor IA' },

  // Compare AI Assistant
  'compare.ai.title': { en: 'Not sure? Let AI help you choose.', es: '¿No está seguro? Deje que la IA le ayude.' },
  'compare.ai.subtitle': { en: 'Tell us how you bank, and we will recommend the best account.', es: 'Cuéntenos cómo usa su banco y le recomendaremos la mejor cuenta.' },
  'compare.ai.placeholder': { en: 'e.g., "I keep about $500 in my account and use ATMs often..."', es: 'ej., "Mantengo unos $500 en mi cuenta y uso cajeros a menudo..."' },
  'compare.ai.analyze': { en: 'Analyze Recommendation', es: 'Analizar Recomendación' },
  'compare.ai.analyzing': { en: 'Analyzing...', es: 'Analizando...' },
  'compare.ai.result': { en: 'We Recommend:', es: 'Recomendamos:' },

  // Locations Page
  'loc.title': { en: 'Find a Branch or ATM', es: 'Buscar Sucursal o Cajero' },
  'loc.search.placeholder': { en: 'City, State, or Zip', es: 'Ciudad, Estado o Código Postal' },
  'loc.filter': { en: 'Filter', es: 'Filtros' },
  'loc.paris': { en: 'Paris Main Bank', es: 'Banco Principal de Paris' },
  'loc.reno': { en: 'Reno Branch', es: 'Sucursal de Reno' },
  'loc.celina': { en: 'Celina Branch', es: 'Sucursal de Celina' },
  'loc.ftworth': { en: 'North Tarrant Branch', es: 'Sucursal de North Tarrant' },
  'loc.frisco': { en: 'Frisco Branch', es: 'Sucursal de Frisco' },
  'loc.plano': { en: 'Plano Loan Production Office', es: 'Oficina de Préstamos de Plano' },
  'loc.bryan': { en: 'Bryan Loan Production Office', es: 'Oficina de Préstamos de Bryan' },
  'loc.hours.lobby': { en: 'Lobby', es: 'Vestíbulo' },
  'loc.hours.drive': { en: 'Drive-Thru', es: 'Autobanco' },
  'loc.call': { en: 'Call', es: 'Llamar' },
  'loc.directions': { en: 'Directions', es: 'Direcciones' },
  'loc.map.notice': { en: 'Map view is simulated.', es: 'La vista del mapa es simulada.' },

  // Security Page
  'sec.title': { en: 'Security Center', es: 'Centro de Seguridad' },
  'sec.subtitle': { en: 'Protecting your financial well-being is our top priority. Use our AI tools to detect potential threats.', es: 'Proteger su bienestar financiero es nuestra principal prioridad. Utilice nuestras herramientas de IA para detectar posibles amenazas.' },
  'sec.scam.title': { en: 'AI Scam Detector', es: 'Detector de Estafas con IA' },
  'sec.scam.desc': { en: 'Received a suspicious text or email? Paste it below, and our AI will analyze it for signs of fraud.', es: '¿Recibió un mensaje de texto o correo sospechoso? Péguelo a continuación y nuestra IA lo analizará en busca de signos de fraude.' },
  'sec.scam.placeholder': { en: 'Paste the suspicious message here (e.g., "Urgent: Your account has been suspended...")', es: 'Pegue el mensaje sospechoso aquí (ej., "Urgente: Su cuenta ha sido suspendida...")' },
  'sec.scam.btn': { en: 'Analyze Message', es: 'Analizar Mensaje' },
  'sec.scam.analyzing': { en: 'Scanning for threats...', es: 'Escaneando amenazas...' },
  'sec.result.safe': { en: 'Likely Safe', es: 'Probablemente Seguro' },
  'sec.result.suspicious': { en: 'Suspicious', es: 'Sospechoso' },
  'sec.result.danger': { en: 'High Risk', es: 'Alto Riesgo' },
  'sec.tips.title': { en: 'Security Tips', es: 'Consejos de Seguridad' },
  'sec.tips.1': { en: 'Never share your password or PIN.', es: 'Nunca comparta su contraseña o PIN.' },
  'sec.tips.2': { en: 'Lamar National will never ask for sensitive info via text.', es: 'Lamar National nunca pedirá información confidencial por mensaje de texto.' },
  'sec.tips.3': { en: 'Enable multi-factor authentication.', es: 'Habilite la autenticación multifactor.' },
  'sec.footer': { en: 'Powered by Gemini. AI results are for informational purposes only. When in doubt, call us directly.', es: 'Potenciado por Gemini. Los resultados de la IA son solo para fines informativos. En caso de duda, llámenos directamente.' },

  // Education Page
  'edu.title': { en: 'Financial Education Center', es: 'Centro de Educación Financiera' },
  'edu.subtitle': { en: 'Empowering our community with knowledge. Use our AI tools to demystify complex financial terms and build your future.', es: 'Empoderando a nuestra comunidad con conocimiento. Use nuestras herramientas de IA para desmitificar términos financieros complejos y construir su futuro.' },
  'edu.jargon.title': { en: 'Jargon Buster', es: 'Explicador de Términos' },
  'edu.jargon.desc': { en: 'Confused by bank speak? Type a term (like "Escrow" or "APY") and get a simple explanation with a real-world analogy.', es: '¿Confundido por el lenguaje bancario? Escriba un término (como "Escrow" o "APY") y obtenga una explicación simple con una analogía del mundo real.' },
  'edu.jargon.placeholder': { en: 'Enter a term e.g., "Amortization"', es: 'Ingrese un término ej., "Amortización"' },
  'edu.jargon.btn': { en: 'Explain it to me', es: 'Explícamelo' },
  'edu.path.title': { en: 'Personalized Pathways', es: 'Rutas Personalizadas' },
  'edu.path.desc': { en: 'Choose a financial goal and get a 3-step action plan generated just for you.', es: 'Elija una meta financiera y obtenga un plan de acción de 3 pasos generado solo para usted.' },
  'edu.path.home': { en: 'Buying a Home', es: 'Comprar una Casa' },
  'edu.path.credit': { en: 'Building Credit', es: 'Construir Crédito' },
  'edu.path.retire': { en: 'Retirement', es: 'Jubilación' },
  'edu.result.analogy': { en: 'Analogy:', es: 'Analogía:' },
  'edu.gen.plan': { en: 'Generating your plan...', es: 'Generando su plan...' },
  'edu.plan.header': { en: 'Your Action Plan:', es: 'Su Plan de Acción:' },
  'edu.cta.title': { en: 'Want to dive deeper?', es: '¿Quiere profundizar más?' },
  'edu.cta.desc': { en: 'Our team of local bankers is always ready to sit down and discuss your financial future over a cup of coffee. No AI required.', es: 'Nuestro equipo de banqueros locales siempre está listo para sentarse y hablar sobre su futuro financiero con una taza de café. No se requiere IA.' },
  'edu.cta.btn': { en: 'Schedule an Appointment', es: 'Programar Cita' },

  // SEO Content Expansion
  'seo.content.title': { en: 'Our Service in Texas', es: 'Nuestro Servicio en Texas' },
  'seo.content.p1': {
    en: 'At Lamar National Bank, we don\'t just provide accounts; we power progress in every community we serve. In Paris, we are the go-to partner for small business growth through specialized SBA lending. In Celina and Frisco, our commercial banking teams work on the ground to fund development and machinery that drives the local economy.',
    es: 'En Lamar National Bank, no solo proporcionamos cuentas; impulsamos el progreso en cada comunidad a la que servimos. En Paris, somos el socio ideal para el crecimiento de las pequeñas empresas a través de préstamos especializados de la SBA. En Celina y Frisco, nuestros equipos de banca comercial trabajan sobre el terreno para financiar el desarrollo y la maquinaria que impulsa la economía local.'
  },
  'seo.content.p2': {
    en: 'Whether you\'re looking for a personal mortgage in Frisco or wealth management in North Tarrant, you\'ll find a local banker who understands your neighborhood. We believe in banking that\'s as big as Texas but as personal as a handshake.',
    es: 'Ya sea que busque una hipoteca personal en Frisco o gestión de patrimonio en North Tarrant, encontrará un banquero local que comprende su vecindario. Creemos en una banca que es tan grande como Texas pero tan personal como un apretón de manos.'
  },
  'seo.content.keywords': {
    en: 'Texas Community Banking, Commercial Loans Paris TX, SBA Preferred Lender, North Texas Mortgages, Celina Business Banking, Frisco Financial Services, Personal Checking Accounts Texas.',
    es: 'Banca Comunitaria de Texas, Préstamos Comerciales Paris TX, Prestamista Preferido de la SBA, Hipotecas del Norte de Texas, Banca Comercial de Celina, Servicios Financieros de Frisco, Cuentas de Cheques Personales en Texas.'
  },

  // FAQ for Schema
  'faq.q1': { en: 'What services does Lamar National Bank offer?', es: '¿Qué servicios ofrece Lamar National Bank?' },
  'faq.a1': { en: 'We offer a full suite of personal and business banking services, including checking and savings accounts, commercial lending, mortgage solutions, and advanced digital banking tools.', es: 'Ofrecemos un conjunto completo de servicios bancarios personales y comerciales, que incluyen cuentas de cheques y ahorros, préstamos comerciales, soluciones hipotecarias y herramientas avanzadas de banca digital.' },
  'faq.q2': { en: 'Where are your branches located?', es: '¿Dónde se encuentran sus sucursales?' },
  'faq.a2': { en: 'We have branches and loan production offices in Paris, Reno, Celina, North Tarrant, Frisco, Plano, and Bryan, Texas.', es: 'Tenemos sucursales y oficinas de préstamos en Paris, Reno, Celina, North Tarrant, Frisco, Plano y Bryan, Texas.' },
  'faq.q3': { en: 'Do you offer online and mobile banking?', es: '¿Ofrecen banca en línea y móvil?' },
  'faq.a3': { en: 'Yes, our modern digital banking platform allows you to manage accounts, deposit checks, and transfer funds securely from any device.', es: 'Sí, nuestra moderna plataforma de banca digital le permite administrar cuentas, depositar cheques y transferir fondos de forma segura desde cualquier dispositivo.' },

  // Expanded Geo Q&A
  'faq.q4': { en: 'Does Lamar National Bank offer SBA loans in Paris, TX?', es: '¿Ofrece Lamar National Bank préstamos de la SBA en Paris, TX?' },
  'faq.a4': { en: 'Yes, we are a preferred SBA lender serving Paris and the surrounding Lamar County area, helping small businesses secure the funding they need to grow.', es: 'Sí, somos un prestamista preferido de la SBA que sirve a Paris y el área circundante del condado de Lamar, ayudando a las pequeñas empresas a obtener el financiamiento que necesitan para crecer.' },
  'faq.q5': { en: 'Where can I find a commercial lender in Frisco or Celina?', es: '¿Dónde puedo encontrar un prestamista comercial en Frisco o Celina?' },
  'faq.a5': { en: 'We have dedicated commercial lending teams in our Frisco and Celina branches specializing in real estate, equipment, and working capital loans for North Texas businesses.', es: 'Tenemos equipos dedicados de préstamos comerciales en nuestras sucursales de Frisco y Celina que se especializan en préstamos para bienes raíces, equipos y capital de trabajo para empresas del norte de Texas.' },
  'faq.q6': { en: 'What sets Lamar National apart from big banks in Texas?', es: '¿Qué diferencia a Lamar National de los grandes bancos de Texas?' },
  'faq.a6': { en: 'As a relationship-first community bank, our decisions are made locally in Texas. You get direct access to decision-makers and a banker who understands the specific needs of your community.', es: 'Como banco comunitario de relación primero, nuestras decisiones se toman localmente en Texas. Obtiene acceso directo a los tomadores de decisiones y a un banquero que comprende las necesidades específicas de su comunidad.' },
};

export const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => { },
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[key]?.[language] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
